#!/bin/sh

compiler=gcc
optimisation=3
warnings="-Wunused-label -Wunused-value -Wunused-variable"
guile_include="$(guile-config compile)"
guile_libs="$(guile-config link)"
compiler_options="-Wl,--version-script=other/shared-library-exports -shared -fpic -lsph-db -Wfatal-errors $warnings -std=c11 -O$optimisation $guile_libs"
target_dir=tmp
target="$target_dir/libguile-sph-db.so"
source=source/c-precompiled/main.c

compile_c() {
  $compiler $guile_include $compiler_options "$source" -o "$target"
}

mkdir -p "$target_dir" &&
compile_c &&
chmod -R 755 "$target_dir" &&
chmod 644 "$target"
compile_c
