#!/usr/bin/env guile
!#

; depends on sph-lib. can be called with --help

(import (sph install))

(install-cli
  (system-libraries "temp/libguile-sph-db.so")
  (guile-site-modules "source/scheme/sph" "source/scheme/test"))
