#!/bin/sh -e

# usage: ./exe/install [path-prefix]

prefix="$1"
lib_dir="$prefix/usr/lib"
guile_dir="$prefix/usr/share/guile/site"

mkdir -p "$lib_dir" "$guile_dir"
cp -t "$lib_dir" "tmp/libguile-sph-db.so"
cp -rt "$guile_dir" "source/scheme/sph" "source/scheme/test"
find "$guile_dir/sph" "$lib_dir/libguile-sph-db.so" -type d -exec chmod 755 {} \;
find "$guile_dir/sph" "$lib_dir/libguile-sph-db.so" -type f -exec chmod 644 {} \;
